### ISSUE TITLE
Drop this project

### ISSUE THREAD

**Issue by KrisSiegel** [phillro/node-elasticsearch-client#121]
When conducting a Google search for "elasticsearch node" this is the first result that pops up. Unfortunately it hasn't been maintained in quite some time and it seems to have difficulty working with the latest version of elastic search. Therefore I am suggesting dropping this project.

**Comment by DinisCruz** [comment]
Also isn't the https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/index.html more complete and up-to-date now?

**Comment by phillro** [comment]
It is. I'd use that ;)

Not maintaining this anymore.

**Comment by KrisSiegel** [comment]
Could you at least update the README to point to that?
